language: python
python:
 - 2.7
sudo: false
env:
 - TOX_ENV=py27
 - TOX_ENV=docs
 - TOX_ENV=lint
install:
 - pip install tox
 - pip install coveralls
script:
 - tox -e $TOX_ENV
after_success:
 - coveralls
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
